---
- name: Configure MySQL default authentication plugin
  ansible.builtin.lineinfile:
    path: /etc/my.cnf.d/mysql-server.cnf
    line: "default-authentication-plugin=mysql_native_password"
    create: yes


- name: Update MySQL service limit
  ansible.builtin.replace:
    path: /usr/lib/systemd/system/mysqld.service
    regexp: 'LimitNOFILE\s*=\s*\d+'
    replace: 'LimitNOFILE = 32000'

- name: daemon reload
  command: systemctl daemon-reload 

- name: start and enabled the mysqld
  service:
    name: mysqld
    enabled: true
    state: restarted

- name: set the php time zone
  lineinfile:
    line: 'date.timezone = Europe/Paris'
    regexp: '^date.timezone'
    path: /etc/php.d/50-centreon.ini
    create: yes

- name: restart the php-fpm service
  service:
    name: php-fpm
    state: restarted

- name: Enable Centreon and related services
  ansible.builtin.service:
    name: "{{ item }}"
    enabled: yes
  loop:
    - php-fpm
    - httpd
    - centreon
    - cbd
    - centengine
    - gorgoned
    - snmptrapd
    - centreontrapd
    - snmpd


- name: Enable and start crond
  ansible.builtin.service:
    name: crond
    state: started
    enabled: yes

- name: start and enabled the mysqld
  service:
    name: mysqld
    enabled: true
    state: restarted

#- name: Add $hostCentreon configuration to /etc/centreon/conf.pm
#  lineinfile:
#    path: /etc/centreon/conf.pm
#    line: '$hostCentreon = "{{ ansible_default_ipv4.address }}"'
#    create: yes  # This will create the file if it does not exist
#    regexp: '^$hostCentreon'
#    state: present  # Ensures the line is added if not present
#    backup: yes  # Optionally backup the file before making changes

#- name: Clear Centreon cache
#  command: rm -rf /var/cache/centreon/*





