--- 
- name: Set MySQL root password
  mysql_user:
    name: root
    password: "{{ mysql_root_password }}"
    host: localhost
    login_user: root
    login_password: "{{ default_mysql_root_password }}"
    state: present
    
- name: Remove anonymous MySQL users
  mysql_user:
    name: ""
    state: absent
    login_user: root
    login_password: "{{ mysql_root_password }}"
    
- name: Remove test database
  mysql_db:
    name: "{{ item }}"
    state: absent
    login_user: root
    login_password: "{{ mysql_root_password }}"
  loop:
    - test

#- name: Drop centreon DB
#  mysql_query:
#    login_user: root
#    login_password: "Redhat@12345"
#    query: "{{ item }}"
#  loop:
#    - "DROP DATABASE centreon;"
#    - "DROP DATABASE centreon_storage;"

#- name: Reload privilege tables
#  mysql_query:
#    query: "FLUSH PRIVILEGES;"
#    login_user: root
#    login_password: "Redhat@12345"

- name: Reload privilege tables
  shell: mysql -u root -p"{{ mysql_root_password }}" -e "FLUSH PRIVILEGES;"

