---

- name: Install dnf-plugins-core
  ansible.builtin.yum:
    name: dnf-plugins-core
    state: present

- name: Reset PHP module
  ansible.builtin.command:
    cmd: dnf module reset php -y

- name: Install PHP 8.1 module from Remi
  ansible.builtin.command:
    cmd: dnf module install php:remi-8.1 -y

- name: Clean all DNF metadata and enable all repositories
  ansible.builtin.command:
    cmd: dnf clean all --enablerepo=*

- name: Update all packages to the latest version
  ansible.builtin.dnf:
    name: "*"
    state: latest

- name: Install MySQL, Centreon server
  ansible.builtin.yum:
    name:
      - mysql-server
      - mysql
      - python3
      - python3-pip
      - centreon-mysql
      - centreon
    state: present

- name: Install pymysql
  ansible.builtin.shell:
    cmd: pip3 install pymysql 
  register: install_output
