- name: Ensure SELinux is disabled
  ansible.builtin.replace:
    path: /etc/selinux/config
    regexp: '^SELINUX=.*'
    replace: 'SELINUX=disabled'
- name: Stop and disable firewalld
  ansible.builtin.service:
    name: firewalld
    state: stopped
    enabled: no

- name: Install dnf-plugins-core
  ansible.builtin.yum:
    name: dnf-plugins-core
    state: present

- name: Install EPEL release
  ansible.builtin.yum:
    name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
    state: present

- name: Enable CodeReady Builder repository
  ansible.builtin.command:
    cmd: subscription-manager repos --enable codeready-builder-for-rhel-8-x86_64-rpms
    creates: /etc/yum.repos.d/redhat.repo

- name: Add Centreon repository
  ansible.builtin.yum_repository:
    name: centreon
    description: Centreon Repository
    baseurl: https://packages.centreon.com/rpm-standard/24.10/el8/centreon-24.10.repo
    enabled: yes
    gpgcheck: yes

- name: Clean all dnf caches
  ansible.builtin.command:
    cmd: dnf clean all --enablerepo=*

- name: Install dnf-plugins-core
  ansible.builtin.yum:
    name: centreon-poller
    state: present

- name: Enable Centreon and related services
  ansible.builtin.service:
    name:
      - centreon
      - centengine
      - gorgoned
    enabled: yes

- name: Enable and start centreontrapd
  ansible.builtin.service:
    name: centreontrapd
    state: started
    enabled: yes

- name: Enable and start snmptrapd
  ansible.builtin.service:
    name: snmptrapd
    state: started
    enabled: yes

- name: Enable and start gorgoned
  ansible.builtin.service:
    name: gorgoned
    state: started
    enabled: yes

- name: Enable and start gorgoned
  ansible.builtin.service:
    name: centengine
    state: restarted
 

